### ISSUE TITLE
Scrollable brightnessctl waybar applet broken

### ISSUE THREAD

**Issue by g5ostXa** [g5ostXa/hyprarch2#70]
- Temp workaround:
[`lumine.sh`](https://github.com/g5ostXa/hyprarch2/blob/master/src/Scripts/lumine.sh)

- Terminal command:
```
$ lumine
```

**Comment by khushal-banks** [comment]
Hi @g5ostXa, can you describe more about this issue?

Following is what i use for `brightnessctl`
```
   "backlight": {
        "format": " {icon} ",
        "format-alt": " {icon} {percent}% ",
        "format-icons": ["", "", "", "", "", "", "", "", ""],
        "on-scroll-up": "brightnessctl set 1%+",
        "on-scroll-down": "brightnessctl set 1%-",
        "scroll-step": "0.2",
        "reverse-scrolling": false,
        "on-click-right": "brightnessctl set 1%-",
        "tooltip": true,
        "tooltip-format": "Brightness: {percent}%",
    },
```

**Comment by g5ostXa** [comment]
Well basically, the applet stopped allowing me to scroll up and down to set my laptop screen brightness.

All it does now is telling me the current brightness. 

Didn't yet have time to check it out so I created this issue. 

Probably just a recent brightnessctl update related issue, but I'm not sure.

- My brightnessctl waybar module:
```
  "backlight": {
        "format": "{icon} {percent}%",
        "format-icons": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        "scroll-step": 1
    }
```

**Comment by khushal-banks** [comment]
> Probably just a recent brightnessctl update related issue, but I'm not sure.

Most likely, it is an update.
I also encountered something like this yesterday.

check by running following command from terminal and check if it is asking for password/permission.

For example,
`brightnessctl set 56%`

**Comment by g5ostXa** [comment]
> If above command is asking for password/permission then add your user to video group and reboot the system.
sudo gpasswd -a <user_name> video && reboot
You may check usergroups for current user by using groups command

Yeah it works and my user is already in the group `video`. 
`gpasswd` wouldn't work bc I'm using `systemd-homed` and user must be added to groups via `homectl`.

---

> Most likely, it is an update.
I also encountered something like this yesterday.

- What is the issue that you encountered with the applet and how did you fix it, if you don't mind?

**Comment by khushal-banks** [comment]
I was not able to use brightnessctl even on terminal because my user was not in video group.
If your command works on terminal then, maybe just assign `on-scroll-up` & `on-scroll-down`

```
"on-scroll-up": "brightnessctl set 1%+",
"on-scroll-down": "brightnessctl set 1%-",
```

**Comment by g5ostXa** [comment]
Will try.

**Comment by g5ostXa** [comment]
> I was not able to use brightnessctl even on terminal because my user was not in video group.
If your command works on terminal then, maybe just assign on-scroll-up & on-scroll-down

It worked. Thanks!
