### ISSUE TITLE
Change `dotfiles/starship/`symlink

### ISSUE THREAD

**Issue by g5ostXa** [g5ostXa/hyprarch2#76]
Edit `src/.install/setup.sh` and find the `_create_symlinks_`
function.

In there you'll find a cmd that creates a symbolic link for `starship`:
```
ln -s ~/dotfiles/starship/ ~/.config/
```

Modify the source of the symlink to `~/dotfiles/starship/starship.toml`:
```
ln -s ~/dotfiles/starship/starship.toml ~/.config/
```

**Comment by khushal-banks** [comment]
[Here](https://github.com/g5ostXa/hyprarch2/blob/b7ee57ff496d736fdeb78691a707dfce9aa745b4/src/.install/setup.sh#L159)
